### ISSUE TITLE
Travel summary bar grey out

### ISSUE THREAD

**Issue by dpdavids** [icefoganalytics/travel-authorization#154]
On a travel auth the top bar has purpose and dates etc.  It looks like I should be able to edit these items (which I can't and that is correct)  I am hoping we could grey out the fields or something so that it is obvious that the user can't do.

**Comment by klondikemarlen** [comment]
@dpdavids This is something that I've been wondering for a while. The library we are using Vuetify uses this formatting for "readonly" fields. There is also the "disabled" flag, but the contrast is so low that its very hard to read.

using readonly
![image](https://github.com/icefoganalytics/travel-authorization/assets/23045206/7e3f03c9-4f01-42de-ad26-bc3ba88df4a2)

using "disabled"
![image](https://github.com/icefoganalytics/travel-authorization/assets/23045206/e7442208-f955-4e08-bc34-df3e56cff3de)

I think it might be a good idea to build display read only data completely differently?
i.e. instead of making the look like a form field, why not just make it data?
Like this but prettier:
![image](https://github.com/icefoganalytics/travel-authorization/assets/23045206/ce7864ed-8d04-479c-9101-20ada74acab5)

**Comment by dpdavids** [comment]
I like it! Sorry for the late response.  way to keep it going!

**Comment by klondikemarlen** [comment]
Completed by @datajohnson in https://github.com/ytgov/travel-authorization/pull/81
